apiVersion: v1
kind: Service
metadata:
  name: absence
  namespace: esprit-portail-entreprise-prod
  labels:
    app:  portail-entreprise
    portail-entreprise.service: absence
spec:    
  type: ClusterIP
  ports:
    - name: "http"
      port: 1923
      targetPort: 1923
    
  selector:
    app: portail-entreprise
    portail-entreprise.service: absence
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: absence
  namespace: esprit-portail-entreprise
  labels:
    app: portail-entreprise
    portail-entreprise.service: absence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portail-entreprise
      portail-entreprise.service: absence
  template:
    metadata:
      labels:
        app: portail-entreprise
        portail-entreprise.service: absence
    spec: 
      imagePullSecrets:
        - name: harbor-creds1
      serviceAccountName: esprit-app-sa
      initContainers:
      - name: vault-init
        image: hashicorp/vault:1.15.0
        command: 
        - vault
        - agent
        - -config=/vault/config/esprit-agent.hcl
        - -exit-after-auth
        env:
        - name: VAULT_ADDR
          value: "http://vault.vault.svc.cluster.local:8200"
        volumeMounts:
        - name: vault-config-esprit
          mountPath: /vault/config
        - name: vault-secrets
          mountPath: /vault/secrets 
      containers:
      - name: portail-absence
        image: harbor.pixelslabs.com/projetesprit/esprit-portail-entreprise_absence:v1.4.1
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
          - name: TZ
            value: "Africa/Tunis"
          - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
            value: "health,info,metrics,prometheus"
          - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
            value: "true"
          - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
            value: "true"
        command:
        - sh
        - -c
        - |
          echo "Loading secrets from Vault..."
          if [ -f /vault/secrets/esprit.env ]; then
            set -a  
            . /vault/secrets/esprit.env
            set +a
            echo "Secrets loaded successfully!"
          else
            echo "ERROR: No secrets file found!"
            exit 1
          fi
          exec java -cp /opt/app:/opt/app/lib/* com.dsi.absencems.AbsenceMsApplication
        volumeMounts:
        - name: vault-secrets
          mountPath: /vault/secrets
          readOnly: true
        ports:
        - containerPort: 1923
        readinessProbe:
          httpGet:
            path: /api/absence/actuator/health/readiness
            port: 1923
          initialDelaySeconds: 240
          periodSeconds: 30
          failureThreshold: 3 
        livenessProbe:
          httpGet:
            path: /api/absence/actuator/health/liveness
            port: 1923
          initialDelaySeconds: 240
          periodSeconds: 30
          failureThreshold: 3 
      restartPolicy: Always
      volumes:
      - name: vault-config-esprit
        configMap:
          name: vault-config-esprit
      - name: vault-secrets
        emptyDir: {}   

