apiVersion: v1
kind: Service
metadata:
  name: timetable
  namespace: esprit-portail-entreprise
  labels:
    app:  portail-entreprise
    portail-entreprise.service: timetable
spec:    
  type: ClusterIP
  ports:
    - name: "http"
      port: 1924
      targetPort: 1924
  selector:
    app: portail-entreprise
    portail-entreprise.service: timetable
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timetable
  namespace: esprit-portail-entreprise
  labels:
    app: portail-entreprise
    portail-entreprise.service: timetable
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: portail-entreprise
      portail-entreprise.service: timetable
  template:
    metadata:
      labels:
        app: portail-entreprise
        portail-entreprise.service: timetable
    spec: 
      securityContext:
        fsGroup: 2003
      initContainers:
        - name: volume-permission
          image: busybox
          command: ["sh", "-c", "chmod 775 /mnt/portail-entreprise/data/timetable"]
          volumeMounts:
            - name: timetable-data
              mountPath: /mnt/portail-entreprise/data/timetable
        - name: vault-init
          image: hashicorp/vault:1.15.0
          command: 
            - vault
            - agent
            - -config=/vault/config/esprit-agent.hcl
            - -exit-after-auth
          env:
          - name: VAULT_ADDR
            value: "http://vault.vault.svc.cluster.local:8200"
          volumeMounts:
          - name: vault-config-esprit
            mountPath: /vault/config
          - name: vault-secrets
            mountPath: /vault/secrets 
      serviceAccountName: esprit-app-sa
      imagePullSecrets:
        - name: harbor-creds1
       
      containers:
      - name: portail-timetable
        image: harbor.pixelslabs.com/projetesprit/esprit-portail-entreprise_timetable:3c5d0f058cc876cce6d58d925ec1ce4df7861e9f
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
          - name: TZ
            value: "Africa/Tunis"
        command:
        - sh
        - -c
        - |
          echo "Loading secrets from Vault..."
          if [ -f /vault/secrets/esprit.env ]; then
            set -a  
            . /vault/secrets/esprit.env
            set +a
            echo "Secrets loaded successfully!"
          else
            echo "ERROR: No secrets file found!"
            exit 1
          fi
          exec java -cp opt/app:opt/app/lib/* com.dsi.edtms.EdtMsApplication
        volumeMounts:
        - name: vault-secrets
          mountPath: /vault/secrets
          readOnly: true
        - mountPath: /mnt/portail-entreprise/data/timetable
          name: timetable-data
        ports:
        - containerPort: 1924
        readinessProbe:
          httpGet:
            path: /api/edt/actuator/health/readiness
            port: 1924
          initialDelaySeconds: 240
          periodSeconds: 30
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/edt/actuator/health/liveness
            port: 1924
          initialDelaySeconds: 240
          periodSeconds: 30
          failureThreshold: 3
      restartPolicy: Always
      volumes:
        - name: timetable-data
          persistentVolumeClaim:
            claimName: timetable-data
        - name: vault-config-esprit
          configMap:
            name: vault-config-esprit
        - name: vault-secrets
          emptyDir: {}  
    
