apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timetable-data
  namespace: esprit-portail-entreprise-prod
  labels:
    app: portail-entreprise
    portail-entreprise.service: timetable
spec:
  storageClassName: manual  
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
