apiVersion: v1
kind: PersistentVolume
metadata:
  name: timetable-data-pv-prod
  labels:
    app: portail-entreprise
    portail-entreprise.service: timetable
spec:
  storageClassName: manual  
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany  
  hostPath:
    path: "/var/local"
    type: DirectoryOrCreate  
